//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auth_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
    pub username: String,
    pub password: String,
    pub nickname: String,
    pub remark: Option<String>,
    pub email: Option<String>,
    pub mobile: Option<String>,
    pub sex: Option<i8>,
    pub avatar: Option<String>,
    pub status: i8,
    pub login_ip: Option<String>,
    pub login_time: Option<DateTime>,
    pub create_user_id: Option<i64>,
    pub create_time: DateTime,
    pub update_user_id: i64,
    pub update_time: DateTime,
    pub deleted: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
