//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::web_blog::Entity as WebBlog;
pub use super::web_blog_label::Entity as WebBlogLabel;
pub use super::web_label::Entity as WebLabel;
pub use super::web_type::Entity as WebType;

