//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_menu")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub menu_id: i64,
    pub menu_name: String,
    pub permission: String,
    pub r#type: i8,
    pub sort: i32,
    pub parent_id: i64,
    pub path: Option<String>,
    pub icon: Option<String>,
    pub status: i8,
    pub visible: i8,
    pub create_user_id: i64,
    pub create_time: DateTime,
    pub update_user_id: i64,
    pub update_time: DateTime,
    pub deleted: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
