//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Serialize,Deserialize)]
#[sea_orm(table_name = "web_blog")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_id: i64,
    pub title: String,
    pub summary: String,
    pub type_id: i64,
    pub level: i8,
    pub enable_comment: i8,
    pub status: i8,
    pub html: String,
    pub md: String,
    pub create_user_id: i64,
    pub create_time: DateTime,
    pub update_user_id: i64,
    pub update_time: DateTime,
    pub deleted: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
