//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "web_label")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub label_id: i64,
    pub label_name: String,
    pub create_user_id: i64,
    pub create_time: DateTime,
    pub update_user_id: i64,
    pub update_time: DateTime,
    pub deleted: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
