//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "web_blog_label")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub label_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
