
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nuxt-web
  name: nuxt-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nuxt-web
  template:
    metadata:
      labels:
        app: nuxt-web
    spec:
      containers:
        - name: nuxt-web
          image: registry.cn-shanghai.aliyuncs.com/wccloud/nuxt_web
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: timezone
              mountPath: /etc/timezone
              readOnly: true
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          hostPath:
            path: /etc/timezone
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          effect: "NoSchedule"
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: nuxt-web
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nuxt-web
  name: nuxt-web
spec:
  ports:
    - port: 8000
      name: nuxt-web-service80
      protocol: TCP
      targetPort: 8000
  selector:
    app: nuxt-web
  clusterIP: 10.96.2.2
