server:
  port: 8084

spring:
  main:
    allow-circular-references: true
  application:
    name: wccloud-admin-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      server-addr: home0122:8848
      username: nacos
      password: nacos
      discovery:
        namespace: wccloud-dev
  data:
    redis:
      host: home0122
      port: 6379
      password: V9fqvTFmQuwhWao2AEqzEHDFH9RnA5YZ
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 9eD4PYotLh9f7u2KJnqxUCyX3kQZSXhn
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://home0122:3306/wccloud_blog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=Asia/Shanghai
  cache:
    type: REDIS
    redis:
      key-prefix: "wccloud-admin-server:spring-cache:"
      time-to-live: 1h

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  swagger-ui:
    enabled: true
  #    path: /doc.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: top.wccloud
