version: '3'

services:
  nuxi_admin:
    image: nuxi_admin:latest
    build:
      context: ../nuxt_admin
      dockerfile: ../nuxt_admin/Dockerfile
    container_name: nuxi_admin
    restart: always
    ports:
      - "8001:8001"
    networks:
      - docker_network
    volumes:
      - /etc/hosts:/etc/hosts
networks:
  docker_network:
    driver: bridge
