version: '3'

services:
  wccloud_web:
    image: nuxi_web:latest
    build:
      context: ../nuxt_web
      dockerfile: ../nuxt_web/Dockerfile
    container_name: nuxi_web
    restart: always
    ports:
      - "8000:8000"
    networks:
      - docker_network
    volumes:
      - /etc/hosts:/etc/hosts
networks:
  docker_network:
    driver: bridge
