version: '3'

services:
  nuxt_admin:
    image: nuxt_admin:latest
    build:
      context: ../nuxt_admin
      dockerfile: Dockerfile
    container_name: nuxt_admin
    restart: always
    ports:
      - "8001:8001"
    networks:
      - docker_network
    volumes:
      - /etc/hosts:/etc/hosts
networks:
  docker_network:
    driver: bridge
