version: '3'

services:
  nuxt_web:
    image: registry.cn-shanghai.aliyuncs.com/wccloud/nuxt_web:latest
    build:
      context: ../nuxt_web
      dockerfile: Dockerfile
    container_name: nuxt_web
    restart: always
    ports:
      - "8000:8000"
    networks:
      - docker_network
    volumes:
      - /etc/hosts:/etc/hosts
networks:
  docker_network:
    driver: bridge
