version: '3'

services:
  wccloud-auth:
    image: wccloud-auth:latest
    build:
      context: ../wccloud-auth
      dockerfile: Dockerfile
    container_name: wccloud-auth
    restart: always
    ports:
      - "8082:8082"
    networks:
      - docker_network
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/skywalking-agent:/home/skywalking-agent
networks:
  docker_network:
    driver: bridge