version: '3'

services:
  wccloud_web:
    image: nuxi_web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxi_web
    restart: always
    ports:
      - "3001:3001"
    networks:
      - docker_network
    volumes:
      - /etc/hosts:/etc/hosts
networks:
  docker_network:
    driver: bridge
