server:
  port: 8081
spring:
  application:
    name: wccloud-gateway-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    redis:
      host: home0122
      port: 6379
      password: V9fqvTFmQuwhWao2AEqzEHDFH9RnA5YZ
  cloud:
    nacos:
      server-addr: home0122:8848
      username: nacos
      password: nacos
      discovery:
        namespace: wccloud-dev
      config:
        namespace: wccloud-dev
        name: ${spring.application.name}
        file-extension: yml

    gateway:
      routes:
        - id: auth
          uri: lb://wccloud-auth-server
          predicates:
            - Path=/wccloud-auth-server/**
          filters:
            - StripPrefix=1
        - id: web
          uri: lb://wccloud-web-server
          predicates:
            - Path=/wccloud-web-server/**
          filters:
            - StripPrefix=1
        - id: admin
          uri: lb://wccloud-admin-server
          predicates:
            - Path=/wccloud-admin-server/**
          filters:
            - StripPrefix=1
        - id: web
          uri: lb://wccloud-web-rust
          predicates:
            - Path=/wccloud-web-rust/**
          filters:
            - StripPrefix=1
