server:
  port: 8082
spring:
  main:
    allow-circular-references: true
  application:
    name: wccloud-auth-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          blog:
            provider: blog
            client-id: blog
            client-secret: blog-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/blog
            scope: openid,profile
            client-name: wccloud-blog
        provider:
          blog:
            authorization-uri: http://localhost:8082/oauth2/authorize
            token-uri: http://localhost:8082/oauth2/token
            jwk-set-uri: http://localhost:8082/oauth2/jwks
  cloud:
    nacos:
      server-addr: localhost:8849
      username: nacos
      password: nacos
      discovery:
        namespace: wccloud
  data:
    redis:
      host: home0122
      port: 6379
      password: V9fqvTFmQuwhWao2AEqzEHDFH9RnA5YZ
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 9eD4PYotLh9f7u2KJnqxUCyX3kQZSXhn
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://home0122:3306/wccloud_blog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=Asia/Shanghai
  cache:
    type: REDIS
    redis:
      key-prefix: "wccloud-auth-server:spring-cache:"
      time-to-live: 1h
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  type-aliases-package: top.wccloud
knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  swagger-ui:
    enabled: true
  #    path: /doc.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: top.wccloud
decorator:
  datasource:
    p6spy:
      # 全部可用参数参照该类：com.p6spy.engine.spy.appender.CustomLineFormat
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类的作用仅仅是改变了打印的颜色，如果不需要可以不加
