server:
  port: 8085
spring:
  application:
    name: wccloud-web-rust
  cloud:
    nacos:
      server-addr: home0122:8848
      username: nacos
      password: nacos
      discovery:
        namespace: wccloud-pro
      config:
        namespace: ${spring.cloud.nacos.discovery.namespace}
        name: wccloud-shared
        file-extension: yaml

